### ISSUE TITLE
Consider support function aliases

### ISSUE THREAD

**Issue by Dentrax** [MichaelAquilina/zsh-you-should-use#110]
# Issue Details

Right now, `you-should-use` only recognizes aliases if command given well: `alias gs='git status`. But this not works for function aliases. It should better if it recognize this type of aliases: `alias my_alias='my_custom_function [COMMANDS] [FLAGS] [OPTIONS]`

## Operating System (uname -a)

`Darwin XXX 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64`

## zsh version (zsh --version)

`zsh 5.8 (x86_64-apple-darwin20.1.0)`

## you-should-use version (echo "$YSU_VERSION")

`1.7.3`

## How is zsh-you-should-use installed?

- [ ] zplug
- [ ] oh-my-zsh
- [X] Antigen
- [ ] Other (please specify)

## Steps to reproduce the issue

1. Create a `function.zsh` file
2. Create an alias function:

```bash
_my_git() {
  # my some other special stuffs here
  git "$@"
}
```
3. Define an `alias` to that function in your `aliases.zsh` file:

```bash
alias gs='_my_git status --short --branch --show-stash'
```
4. Source the `.zsh` files in your `.zshrc` file
5. `$ git status`

Actual:

```bash
Found existing alias for "git status". You should use: "gst"
Found existing git alias for "status". You should use: "git st"
```

Expected:

```bash
Found existing alias for "git status". You should use: "gs"
Found existing alias for "git status". You should use: "gst"
Found existing git alias for "status". You should use: "git st"
```

**Comment by MichaelAquilina** [comment]
I'm not actually sure I understand the problem here. Step 5 does not mention the function in any way so I wouldnt expect one of its aliases to be suggested. Is this a mistake in the issue description or am I just misunderstanding the problem?

**Comment by Dentrax** [comment]
Actually the issue steps are correct. In case we call `gs`, we do not mention the `git` command directly but indirectly in the `_my_git()` function. That's because `_my_git()` takes an `"$@"` for `git` command, which means we are passing whole args to `git` indirectly. In case you ask what happens in these similar cases:

```bash
_my_awesome_func() {
  git "$@"
  echo -n "$1"
  foo "$@"
}
```

```bash
$ alias call_me='_my_awesome_func() status'
```

```bash
$ git status

Found existing alias for "git status". You should use: "call_me"

$ foo status

Found existing alias for "foo status". You should use: "call_me"

$ echo -n "Hello"

Found existing alias for "echo -n". You should use: "call_me"
```

**Comment by Dentrax** [comment]
I think you're right; that's what I thought when I wrote my last comment. :) What I understand is that we should not use functions in aliases to use this plugin properly.

**Comment by MichaelAquilina** [comment]
Thanks for confirming @Dentrax :) going to be closing this issue. Let me know if you think otherwise!
