### ISSUE TITLE
Common aliases

### ISSUE THREAD

**Issue by MikeyBeez** [MichaelAquilina/zsh-you-should-use#111]
Can I add the plugin common-aliases so YSU checks those aliases too?  How would I do that?   Thanks for creating this very helpful plugin.  I think it will transform my workflow.

**Comment by MichaelAquilina** [comment]
If [this is the plugin](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/common-aliases/common-aliases.plugin.zsh) you are referring to, then they should automatically just work with this plugin :)

The installation instructions for this plugin are in the README https://github.com/MichaelAquilina/zsh-you-should-use#installation 

I'm going to mark this issue as closed. But feel free to continue asking questions here if you need more help

**Comment by MikeyBeez** [comment]
From what I can tell, YSU is only working with github.  Here's my plugin line from my .zshrc:  plugins=(you-should-use docker git zsh-navigation-tools zsh-autosuggestions zsh-syntax-highlighting vi-mode common-aliases ubuntu z sudo)  I'm using oh-my-zsh.

**Comment by MichaelAquilina** [comment]
@MikeyBeez what does `echo $YSU_VERSION` display for you?
