### ISSUE TITLE
can not parse you-should-use.plugin.zsh with oh-my-zsh in wsl2

### ISSUE THREAD

**Issue by e365367** [MichaelAquilina/zsh-you-should-use#126]
# Issue Details
After install it, I source my .zshrc file, and then I got error, and I can not use the plugin.
![image](https://github.com/MichaelAquilina/zsh-you-should-use/assets/74970161/2cedc53a-ea02-4911-afe1-a94e75a758cf)

Please provide the following details when opening an issue:

## Operating System (uname -a)  
![image](https://github.com/MichaelAquilina/zsh-you-should-use/assets/74970161/efd5186e-b443-43af-a191-c9292768d1f2)

## zsh version (zsh --version)
![image](https://github.com/MichaelAquilina/zsh-you-should-use/assets/74970161/1d0305bb-1668-472e-83c5-97f26859de6e)

## you-should-use version (echo "$YSU_VERSION")
![image](https://github.com/MichaelAquilina/zsh-you-should-use/assets/74970161/097d0ce4-5467-4c14-a3a7-2eca6c94fdf5)

## How is zsh-you-should-use installed?

- [ ] zplug
- [√] oh-my-zsh
- [ ] Antigen
- [ ] Other (please specify)

**Comment by MichaelAquilina** [comment]
That actually seems quite strange.

What does `head -20 ~/.oh-my-zsh/custom/plugins/you-should-use/you-should-use.plugin.zsh` return?

**Comment by e365367** [comment]
> That actually seems quite strange.
> 
> What does `head -20 ~/.oh-my-zsh/custom/plugins/you-should-use/you-should-use.plugin.zsh` return?

thank you for your reply ！I resolved it just now，it is because the format of the file is windows，I exec the cmd: "dos2unix you-should-use.plugin.zsh" , and then it is ok.

**Comment by MichaelAquilina** [comment]
Nice :) thanks for replying back with what the solution was. Closing this Issue then
