### ISSUE TITLE
Tests failing without modifications

### ISSUE THREAD

**Issue by p1r473** [MichaelAquilina/zsh-you-should-use#132]
# Issue Details
Hi,
I am getting 3 tests failing on a vanilla clone of the repo (with no modifications)
Ive tried this in `zsh -f` with zsh disabled (no .zshrc loaded) and it still fails
```
✘ git aliases substring match
  '' does not contain 'Found existing git alias for "config". You should use: "git cfg"'

✘ git aliases exact match
  '' does not contain 'Found existing git alias for "status". You should use: "git st"'

✘ git aliases match parameters
  '' does not contain 'Found existing git alias for "commit --amend --reuse-message=HEAD". You should use: "git recommit"'

```

Please provide the following details when opening an issue:

## Operating System (uname -a)
Bookworm 12 Linux 6.6.28+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.28-1+rpt1 (2024-04-22) aarch64 GNU/Linux 
## zsh version (zsh --version)
zsh 5.9 (aarch64-unknown-linux-gnu) 
## you-should-use version (echo "$YSU_VERSION")
1.7.3
## How is zsh-you-should-use installed?

- [ ] zplug
- [ ] oh-my-zsh
- [ ] Antigen
- [ X] Other (please specify)
manually sourced
## Steps to reproduce the issue
```
git clone https://github.com/MichaelAquilina/zsh-you-should-use
 cd zsh-you-should-use
 source ./zsh-you-should-use.plugin.zsh
 cd tests
 chmod +x *.zunit
 ./test_aliases.zunit
```
## gist link to your zshrc 
https://gist.githubusercontent.com/p1r473/f9f8e05026e215d57e0d858e32a25975/raw/7f275b0f700f10ae5fec234e3a228a55e0ecd2c0/.zshrc

**Comment by MichaelAquilina** [comment]
hmm that is quite strange actually, I cant understand why it wouldnt be capturing output. What version of zunit are you on?

**Comment by MichaelAquilina** [comment]
I can actually see I have the same issue - something must have broken recently. I'll try look into it today

**Comment by MichaelAquilina** [comment]
Should be working if you pull the latest changes :)
