### ISSUE TITLE
Only show one result for overlapping aliases

### ISSUE THREAD

**Issue by rdnetto** [MichaelAquilina/zsh-you-should-use#2]
I get the following output for `git status`:
```
$ git status
Found existing alias for "git". You should use: "g"
Found existing alias for "git status". You should use: "gs"
```

It would be nice if it only showed the longest matching alias, rather than all of them.

**Comment by MichaelAquilina** [comment]
This is something I was actaully wondering how to handle correctly. 

I think it's useful to see multiple options for aliases that can be used, but I also agree that showing multiple results can be too much to display to the user.

Perhaps I can make this a configurable option.

**Comment by MichaelAquilina** [comment]
How about an option that provides several ways of displaying results. What you suggested could be "Best Match" and the the current could be "All"?

**Comment by MichaelAquilina** [comment]
@rdnetto try out the branch in PR #5 to see if this matches your use case :) The code needs to be cleaned up but works from what I have tested

**Comment by rdnetto** [comment]
Awesome, works great! Thanks for that :)
