### ISSUE TITLE
"Best Match" should take into account all alias types

### ISSUE THREAD

**Issue by selfish** [MichaelAquilina/zsh-you-should-use#30]
![image](https://user-images.githubusercontent.com/7327741/34575204-8d5a3c1a-f182-11e7-8d2f-64a9049b2e7b.png)

While here I typed a bad command anyway (my ignorance using autocomplete), I'd expect to only see the first suggestion, I'll never want to type `git s` because then I should see the `gst` suggestion, so even display it?

This may not be a feature suited for all, but I'd love it as a config option.

**Comment by MichaelAquilina** [comment]
@selfish take a look here and see if this section answers your question: https://github.com/MichaelAquilina/zsh-you-should-use#displaying-results

**Comment by MichaelAquilina** [comment]
Actually, this might be a legitimate bug as it doesnt cater for git and global aliases....

**Comment by selfish** [comment]
I'll try it, thanks for the referral.
I'll use `export YSU_MODE=BESTMATCH`, but please let me know - do I just stick it in my `.zshrc` before the plugin load?

**Comment by MichaelAquilina** [comment]
it can be anywhere in your `.zshrc` file :)

**Comment by selfish** [comment]
Same result after putting it at the top.
(I did of course, tried to re-source the file, and also tried a fresh terminal window)

**Comment by MichaelAquilina** [comment]
Yeah this is definitely a bug. I will try look into it tonight if I get the chance. Thanks for the report!

**Comment by selfish** [comment]
Much obliged.
Your plugin is gold, but your response time is priceless.
Thank you!
