### ISSUE TITLE
false positive in case of common command name prefix?

### ISSUE THREAD

**Issue by emmanueltouzery** [MichaelAquilina/zsh-you-should-use#4]
I just got this false positive:

```
$ gitg
Found existing alias for "git". You should use: "g"
```

i was using https://github.com/jessevdk/gitg (and that command was correctly launched despite the warning)

**Comment by MichaelAquilina** [comment]
Ah yes. Should be an easy fix. Will release it this morning when I get a
chance

**Comment by MichaelAquilina** [comment]
Fixed with https://github.com/MichaelAquilina/zsh-you-should-use/commit/2a57874d6e4b41c8c632998afd88c2f87c056d5c. Give it a go and close the issue if it works for you :)

**Comment by emmanueltouzery** [comment]
yes it seems to fix it! I had found another example btw:

```
$ git mergetool
Found existing alias for "git". You should use: "g"
Found existing alias for "git merge". You should use: "gm"
```

the second one was obviously bogus. closing the bug now, great!
