### ISSUE TITLE
Allow temporary disabling

### ISSUE THREAD

**Issue by HaleTom** [MichaelAquilina/zsh-you-should-use#51]
## Feature request

I'd like to be able to temporarily disable this plugin (eg when generating text to copy / paste when lodging bug reports).

If using:

```
export YSU_MESSAGE_FORMAT=''
```

I simply get the default message format.

Could you support something like:
```
export YSU_DISABLE=1  # any non-null value perhaps
```

**Comment by MichaelAquilina** [comment]
Hi @HaleTom this should be a really easy change so I'll just go ahead and add that in for you.

**Comment by MichaelAquilina** [comment]
@HaleTom try out the functions `disable_you_should_use` and `enable_you_should_use` in the latest release :)

**Comment by HaleTom** [comment]
Excellent!  Thank you!
