### ISSUE TITLE
Support whitelist for ignoring certain commands

### ISSUE THREAD

**Issue by rdnetto** [MichaelAquilina/zsh-you-should-use#7]
My use case for this is that I have `ls` aliased to fix a common typo, but I don't want to be reminded of that every time I run it.
```
$ ls
Found existing alias for "ls". You should use: "sl"
```

**Comment by MichaelAquilina** [comment]
interesting use case. Should also be relatively simple to solve

**Comment by MichaelAquilina** [comment]
Maybe a different approach would be to allow an option that ignores aliases that are of the same length of the command it represents?

**Comment by MichaelAquilina** [comment]
@rdnetto take a look at #8

**Comment by rdnetto** [comment]
Thanks, works perfectly.
