### ISSUE TITLE
RFE: Make project's name less error prone "zsh-"

### ISSUE THREAD

**Issue by BrunoVernay** [MichaelAquilina/zsh-you-should-use#70]
# Issue Details

Different names `you-should-use` vs.  `zsh-you-should-use` can cause issues in **other** projects.   It is error prone.

## How is zsh-you-should-use installed?

- [ ] zplug
- [X] oh-my-zsh
- [ ] Antigen
- [ ] Other (please specify)

## Steps to reproduce the issue

I guess a `oh-my-zsh` wrongly added  `zsh-you-should-use`  in the list of plugin.  Anyway the issue is that other projects were confused with the prefix `zsh-` ...

It is more of an RFE, to make it more straightforward for others to install zsh's `you-should-use` or `zsh-you-should-use`, should you use zsh ...

**Comment by MichaelAquilina** [comment]
I'll take a look at how `oh-my-zsh` is bundling this plugin and see how we can make it work from there. It should be quite simple to rename the plugin file. The only concern I have is how it affects users with existing installations as I've tried this once before and things broke locally for me.

**Comment by MichaelAquilina** [comment]
```
I guess a oh-my-zsh wrongly added zsh-you-should-use in the list of plugin. Anyway the issue is that other projects were confused with the prefix zsh- ...
```

Could you point out where you see this plugin listed in oh-my-zsh? I cant seem to find it at first glance

**Comment by BrunoVernay** [comment]
After some research, it looks like **I** may have added it to the plugin list around 2017 ! The recent change that popped it up is OhMyZSH adding an error message in case of unrecognized plugin :-) 
So, unless you get similar feedback from others, it may just be me 2 years ago being confused and not paying enough attention.

**Comment by MichaelAquilina** [comment]
Going to close this issue based on your last comment @BrunoVernay. Feel free to re-open if you think the issue shouldnt be considered solved.
