### ISSUE TITLE
Getting prompted when using an alias

### ISSUE THREAD

**Issue by epk** [MichaelAquilina/zsh-you-should-use#84]
## Operating System (uname -a)

Darwin Adityas-MacBook-Pro.local 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64

## zsh version (zsh --version)

zsh 5.7.1 (x86_64-apple-darwin19.0.0)

## you-should-use version (echo "$YSU_VERSION")

1.5.0

## How is zsh-you-should-use installed?

- [ ] zplug
- [x] oh-my-zsh
- [ ] Antigen
- [ ] Other (please specify)

## Steps to reproduce the issue

Use any shorthand alias:

```sh
ls
Found existing alias for "ls -G". You should use: "ls"
back
Found existing alias for "cd ..". You should use: "back"
vsc
Found existing alias for "code .". You should use: "vsc"
```

## gist link to your zshrc

https://github.com/epk/dotify/blob/master/.zshrc

**Comment by orcantiryaki** [comment]
Same issue with zplug here

```
$ gss
Found existing alias for "git status -s". You should use: "gss"
.....
```

**Comment by MichaelAquilina** [comment]
Seems like this is a regression from yesterday's release. I'll revert the change temporarily and release a proper fix in due course

**Comment by MichaelAquilina** [comment]
A hotfix has been released that should solve this issue. Let me know if you still experience this problem or not once you update :)

**Comment by orcantiryaki** [comment]
Solved :+1:
