### ISSUE TITLE
Hardcore mode won't block execution

### ISSUE THREAD

**Issue by selfish** [MichaelAquilina/zsh-you-should-use#90]
# Issue Details

Out of thin air, Hardcore mode died on me. I don't believe any specific changes were made in my zshrc that should have broken it.

I have done anything I could think of, including validating my .zshrc, re-installing YSU, etc.

<img width="509" alt="image" src="https://user-images.githubusercontent.com/7327741/69654756-ff653280-107d-11ea-9397-b1f1ad8a5908.png">

This example shows that when in using `echo` instead of my `e` alias, YSU does mention that it knows I'm using hardcore mode, but it won't actually block execution.

Please provide the following details when opening an issue:

## Operating System
`Darwin N-Mac.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64`

## zsh version
`zsh 5.7.1 (x86_64-apple-darwin18.2.0)`

## you-should-use version: 
`1.6.0`

## How is zsh-you-should-use installed?

- [ ] zplug
- [ ] oh-my-zsh
- [x] Antigen
- [ ] Other (please specify)

## Steps to reproduce the issue

Type in any long-form of an alias in Hardcore mode.

## gist link to your zshrc

Lines directly related to YSU are line numbers `76`, `77`, `103`.

https://gist.github.com/selfish/2140c335c5e7bd1168a077a47afafa8d

---

Your help is very very appreciated!!

**Comment by MichaelAquilina** [comment]
That is quite strange, I have the same version of zsh and the plugin and it works correctly for me.

The only thing I can think of is the `kill` command targeting the wrong process due to some plugin that's been installed.

could you try running this in a shell

```
function kill() {
  echo "$@"
  ps -p "${@[3]}"
> }
```

and the running the same command you should me before - and perhaps a few other examples you can think of.

**Comment by selfish** [comment]
I, uh, guess that you were right if I'm reading that correctly?

<img width="473" alt="image" src="https://user-images.githubusercontent.com/7327741/69722322-7a325a00-111f-11ea-8a2f-99b8ae946e24.png">

This process was open before the echo command which triggered the print.

I started a new session (to reset kill) and the result of `which kill` is:
```
kill: shell built-in command
```

Any direction on how to approach that?

I also commented out all of my plugins and reset terminal again (then validated that none of them were working), and tried again, but still, no cigar, YSU fails to block.

**Comment by MichaelAquilina** [comment]
`It appears that romkatv/powerlevel10k or one of it's deps is the cuplrit.`

strange since I also use this, must be a specific setting or a new version that I have not updated to.

I have a few ideas I can experiment with once I can reproduce this issue

**Comment by selfish** [comment]
Here's my .p10k.zsh in case it helps:

https://gist.github.com/e648eb8e240456926d10f8ced3b3068f

**Comment by MichaelAquilina** [comment]
@selfish is this still an issue? I've updated to the latest powerlevel10k for a while now and I still cant reproduce the issue described here.

**Comment by selfish** [comment]
@MichaelAquilina yups.
I've tried everything I could come up with, but nothing seems to make it work again.
I absolutely can't figure out what's causing the problem.

Did you happen to review my p10k config?

Thank you for following up.

**Comment by MichaelAquilina** [comment]
I've actually tried your configuration and still cant seem to reproduce your issue. From looking at your p10k.zsh though it seems like you are using the transient and instant prompt features which tend to cause incompatibility in plugins. Could you check if disabling one of these fixes the issue?

**Comment by selfish** [comment]
I just tried the following, each separately, and all together:

```sh
# .p10k.zsh:
typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off
typeset -g POWERLEVEL9K_INSTANT_PROMPT=off
# Commented out ALL segments on the prompt

# .zshrc:
# Comment out all antigen plugins excluding YSU
# Comment out this:
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
# play around with applying p10k before and after YSU.
```

Bottom line is after I stripped down _everything_, it boils down to:
```sh
antigen theme romkatv/powerlevel10k
```

Even with every possible functionality turned off on p10k, and all plugins enabled on antigen, p10k kills YSU for me. :(

**Comment by selfish** [comment]
Okay!

So after growing desperate, I decided to go batshit crazy:
```sh
antigen update
# Opened a new shell, to find a message saying p10k config is corrupt
antigen reset
# Opened a new shell, EVERYTHING WORKS!
```

@MichaelAquilina thank you for all of your help!
I appreciate the fact that you've tried, and I leave that here for reference.
I have to admit I have no idea what all of it actually did, since I did have the latest version of YSU, and a late version of p10k. But sure, either the update or the cache clear `antigen reset` did the trick.

Again, thanks!

**Comment by MichaelAquilina** [comment]
Thanks for checking @selfish :) Hopefully this was just a very niche bug from a specific version of powerlevel10k. I'll keep an eye out for any similarly reported bugs in the future
